id: P007836
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB4611
  title: ཐུགས་ཆེན་ཀུན་འདུས།
  author: ''
  volumes:
    f0cb581255874401bea93ba7f25643cb:
      image_group_id: I1KG11681
      title: ''
      volume_number: 1
      total_pages: 657
    f73d93924230473eb4828a59fac2e897:
      image_group_id: I1KG11682
      title: ''
      volume_number: 2
      total_pages: 648
    78e1bb36064e4654a0baeb2968bd3b97:
      image_group_id: I1KG11683
      title: ''
      volume_number: 3
      total_pages: 686
    a506197c377f47348df7f2cc143ddf2a:
      image_group_id: I1KG11684
      title: ''
      volume_number: 4
      total_pages: 634
ebook_metadata:
  title: ཐུགས་ཆེན་ཀུན་འདུས།
  author: ''
  sku: P007836
  cover: cover.jpg
  layers:
  - pagination
