id: IAD349F2D
legacy_id: P007836
ocr_import_info:
  bdrc_scan_id: W2DB4611
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T13:57:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T17:23:56.444094+00:00'
last_modified: 2022-09-03 01:28:43.506043
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2DB4611
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2DB4611
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུགས་ཆེན་ཀུན་འདུས།
statistics:
  ocr_word_mean_confidence_index: 0.5409508147723873
  ocr_word_median_confidence_index: 0.5299999713897705
quality: null
bases:
  I1KG11683:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11683
      total_pages: 686
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG11683.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5182348726002023
    legacy_id: v003
  I1KG11684:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11684
      total_pages: 634
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG11684.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5153798297768555
    legacy_id: v004
  I1KG11682:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11682
      total_pages: 648
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG11682.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.551481555334867
    legacy_id: v002
  I1KG11681:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11681
      total_pages: 657
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11681.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5767787127219905
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
