id: IAD349F2D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:03:07+00:00'
last_modified: '2022-06-09T06:23:56.507851+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4611
  title: ཐུགས་ཆེན་ཀུན་འདུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4A54:
      image_group_id: I1KG11681
      title: Volume 1 of thugs chen kun 'dus
      total_pages: 657
      order: 1
      base_file: 4A54.txt
    E7C3:
      image_group_id: I1KG11682
      title: Volume 2 of thugs chen kun 'dus
      total_pages: 648
      order: 2
      base_file: E7C3.txt
    21F5:
      image_group_id: I1KG11683
      title: Volume 3 of thugs chen kun 'dus
      total_pages: 686
      order: 3
      base_file: 21F5.txt
    5E2E:
      image_group_id: I1KG11684
      title: Volume 4 of thugs chen kun 'dus
      total_pages: 634
      order: 4
      base_file: 5E2E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
